services:
  app:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    container_name: app
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 9000:9000
    depends_on:
      - db
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - lamp_php_network

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      # - ./www:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - lamp_php_network

  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lamp_php
      - MYSQL_USER=lamp_php
      - MYSQL_PASSWORD=lamp_php
    restart: unless-stopped
    networks:
      - lamp_php_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - lamp_php_network

volumes:
  mysql_data:
    driver: local

networks:
  lamp_php_network:
    driver: bridge
    name: lamp_php_network